src/conference_room/urls.py
"""Defines url patterns for conference_room app"""

from django.urls import path

from . import views

app_name = 'conference_room'

urlpatterns = [
    path('', views.RoomList.as_view(), name='index'),
    path('new/', views.add_room, name='add-room'),
    path('<int:id>/', views.room_detail, name='room-detail'),
    path('modify/<int:id>/', views.edit_room, name='edit-room'),
    path('delete/<int:id>/', views.delete_room, name='delete-room'),
    path('reserve/<int:id>/', views.book_room, name='book-room'),
    path('search/', views.SearchRoom.as_view(), name='search-room'),
]

src/reservation_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('room/', include('conference_room.urls'))
]

src/conference_room/models.py
from django.db import models


class ConferenceRoom(models.Model):
    name = models.CharField(max_length=255, unique=True)
    capacity = models.PositiveSmallIntegerField()
    projector = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Booking(models.Model):
    room = models.ForeignKey(ConferenceRoom, on_delete=models.CASCADE,
                             related_name='booking')
    date = models.DateField()
    comment = models.TextField()

    class Meta:
        unique_together = ('room', 'date')

    def __str__(self):
        return str(self.date)

src/conference_room/forms.py
import datetime

from django import forms

from .models import Booking, ConferenceRoom


class RoomForm(forms.ModelForm):
    class Meta:
        model = ConferenceRoom
        fields = ['name', 'capacity', 'projector']
        labels = {
            'capacity': 'Num of seats',
            'projector': 'Projector?',
        }


class BookingForm(forms.ModelForm):
    date = forms.DateField(widget=forms.SelectDateWidget())

    class Meta:
        model = Booking
        fields = ['room', 'date', 'comment']
        widgets = {
            'room': forms.HiddenInput(),
            'date': forms.SelectDateWidget(),
            'comment': forms.Textarea(attrs={'placeholder': 'Your comment '
                                                            'here...',
                                             'rows': 20,
                                             'cols': 50})
        }
        labels = {
            'date': '',
            'comment': '',
        }

    def clean_date(self):
        date = self.cleaned_data['date']
        if date < datetime.date.today():
            raise forms.ValidationError("The date cannot be in the past!")
        return date

src/conference_room/views.py
from datetime import date

from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView

from .models import Booking, ConferenceRoom
from .forms import BookingForm, RoomForm


class RoomList(ListView):
    model = ConferenceRoom
    template_name = 'base.html'
    context_object_name = 'rooms'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = date.today()
        return context


class SearchRoom(RoomList):
    template_name = 'search_room.html'

    def get_queryset(self):
        data = self.request.GET
        name = data.get('name', '')
        min_capacity = data.get('min_capacity', '')
        projector = data.get('projector')

        if name != '':
            return ConferenceRoom.objects.filter(name__icontains=name)
        elif min_capacity != '':
            return ConferenceRoom.objects.filter(capacity__gte=min_capacity)
        elif projector == 'on':
            return ConferenceRoom.objects.filter(projector=1)


def add_room(request):
    if request.method != 'POST':
        form = RoomForm()
    else:
        form = RoomForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('conference_room:index')

    context = {
        'form': form
    }
    return render(request, 'add_room.html', context)


def room_detail(request, id):
    room = get_object_or_404(ConferenceRoom, pk=id)
    booking = room.booking.filter(date__gte=date.today()).order_by('date')

    context = {
        'room': room,
        'booking': booking,
    }
    return render(request, 'room_detail.html', context)


def edit_room(request, id):
    room = get_object_or_404(ConferenceRoom, pk=id)
    if request.method != 'POST':
        form = RoomForm(instance=room)
    else:
        form = RoomForm(instance=room, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('conference_room:index')

    context = {
        'room': room, 'form': form
    }
    return render(request, 'edit_room.html', context)


def delete_room(request, id):
    '''

    Delete object with confirm

    '''
    room = get_object_or_404(ConferenceRoom, pk=id)
    if request.method == 'POST':
        room.delete()
        return redirect('conference_room:index')

    context = {
        'room': room
    }
    return render(request, 'delete_room.html', context)


def book_room(request, id):
    room = get_object_or_404(ConferenceRoom, pk=id)
    booking = room.booking.filter(date__gte=date.today()).order_by('date')
    initial_data = {
        'room': room.id
    }
    if request.method != 'POST':
        form = BookingForm(initial=initial_data)
    else:
        form = BookingForm(initial=initial_data, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('conference_room:index')

    context = {
        'room': room, 'form': form, 'booking': booking,
    }
    return render(request, 'book_room.html', context)

src/templates/add_room.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'conference_room:add-room' %}" method='post'>
    {% csrf_token %}
    <h3>Add new room:</h3>
    {{ form.as_p }}
    <p><button name="submit">Add room</button>
    <a href="{% url 'conference_room:index' %}">Cancel</a></p>
</form>

{% endblock content %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book your conference room</title>
</head>
<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #333;
    }

    ul li {
        float: left;
    }

    ul li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }

    ul li a:hover:not(.active) {
        background-color: #111;
    }

    .active {
        background-color: #4CAF50;
    }

    footer {
        text-align: center;
        padding: 3px;
        background-color: #333;
        color: white;
    }

    footer a:link {
        color: white;
    }
</style>

<body>
<ul>
  <li><a class=active href="{% url 'conference_room:index' %}">Main page</a></li>
  <li><a href="{% url 'conference_room:add-room' %}">Add room</a></li>
  <li><a href="{% url 'conference_room:search-room' %}">Search room</a></li>
</ul>

{% block content %}


<ol>
    {% for room in rooms %}

    <li> <a href="{% url 'conference_room:room-detail' room.id %}">
        {{ room.name }}</a>, {{ room.capacity }} seats
        <b>
            {% if room.projector == 1 %} with
                {% else %} without
            {% endif %}
        </b>
        projector.
        {% for obj in room.booking.all %}
            {% if obj.date == today %}
            <i style="color:red;">Booked today</i>
            {% endif %}
        {% endfor %}
        <a href="{% url 'conference_room:edit-room' room.id %}"><button>
            Edit</button></a>
        <a href="{% url 'conference_room:delete-room' room.id %}"><button>
            Delete</button></a>
        <a href="{% url 'conference_room:book-room' room.id %}"><button>
            Book</button></a>
    {% empty %}
    There is no room yet.
    {% endfor %}
</ol>

{% endblock content %}

<footer>
    Author: <a href="mailto:akropiewnicki@gmail.com"> Adam Kropiewnicki</a>
</footer>

</body>
</html>

src/templates/book_room.html
{% extends 'base.html' %}

{% block content %}

<form action="" method='post'>
    {% csrf_token %}
    <h3>Book "{{ room.name }}"</h3>
    {{ form.as_p }}
    <button name="submit">Book room</button>
    <a href="{% url 'conference_room:room-detail' room.id %}">Cancel</a>
</form>

{% if booking %}

<h5>Upcoming bookings:</h5>
<ol>
    {% for book in booking %}
    <li>{{ book.date }} comment: {{ book.comment }}</li>
    {% endfor %}
</ol>

{% endif %}

{% endblock content %}

src/templates/delete_room.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <h1>Do You want to delete the room "{{ room.name }}"?</h1>
    <p><input type="submit" value="Yes"/>
        <a href="{% url 'conference_room:room-detail' room.id %}">Cancel</a></p>
</form>

{% endblock content %}

src/templates/edit_room.html
{% extends 'base.html' %}

{% block content %}

<form action="" method='post'>
    {% csrf_token %}
    <h3>Edit "{{ room.name }}"</h3>
    {{ form.as_p }}
    <p><button name="submit">Save changes</button>
    <a href="{% url 'conference_room:room-detail' room.id %}">Cancel</a></p>
</form>

{% endblock %}

src/templates/room_detail.html
{% extends 'base.html' %}

{% block content %}

<p>
    {% if room %}
    Our conference room "{{ room.name }}" has {{ room.capacity }} seats.<br>
    Projector is
    {% if room.projector == 1 %} available
    {% else %} unavailable
    {% endif %}
    in this room. <br>
    {% endif %}
</p>

<h5>Upcoming bookings:</h5>

    <ol>
        {% for book in booking %}
        <li>{{ book.date }} comment: {{ book.comment }}</li>
        {% empty %}
        No upcoming bookings
        {% endfor %}
    </ol>

<p>
    <a href="{% url 'conference_room:edit-room' room.id %}"><button>
            Edit room</button></a>
    <a href="{% url 'conference_room:delete-room' room.id %}"><button>
            Delete room</button></a>
    <a href="{% url 'conference_room:book-room' room.id %}"><button>
            Book room</button></a>
</p>

{% endblock content %}

src/templates/search_room.html
{% extends "base.html" %}

{% block content %}

<p>
<form action="" method="get">
    <h4>Search by:</h4>
    <input name="name" type="text" placeholder="Name..."><br>
    <input name="min_capacity" type="text" placeholder="Min capacity...">
    <p>Projector: <input name="projector" type="checkbox"></p>
    <p><input type="submit" value="Search"></p>
</form>
</p>

{% if request.GET %}

<h2>Search Results</h2>

<ol>
  {% for room in rooms %}
  <li><a href="{% url 'conference_room:room-detail' room.id %}">
      {{ room.name }} {{ room.capacity }}
      {% if room.projector == 1 %}
      with projector
      {% else %}
      without projector
      {% endif %}</a></li>
  {% empty %}
  Nothing to looking for...
  {% endfor %}
{% endif %}
</ol>

{% endblock content %}